using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MusicList : MonoBehaviour
{
    [Header("ActionThemes Themes")]
    public AudioClip actionMusic0;
    [Range(0, 1)] public float actionMusic0Volume = 0.05f;
    public AudioClip actionMusic1;
    [Range(0, 1)] public float actionMusic1Volume = 0.05f;
    public AudioClip actionMusic2;
    [Range(0, 1)] public float actionMusic2Volume = 0.05f;
    public AudioClip actionMusic3;
    [Range(0, 1)] public float actionMusic3Volume = 0.05f;
    public AudioClip actionMusic4;
    [Range(0, 1)] public float actionMusic4Volume = 0.05f;
    public AudioClip actionMusic5;
    [Range(0, 1)] public float actionMusic5Volume = 0.05f;
    public AudioClip actionMusic6;
    [Range(0, 1)] public float actionMusic6Volume = 0.05f;
    public AudioClip actionMusic7;
    [Range(0, 1)] public float actionMusic7Volume = 0.05f;
    public AudioClip actionMusic8;
    [Range(0, 1)] public float actionMusic8Volume = 0.05f;
    public AudioClip actionMusic9;
    [Range(0, 1)] public float actionMusic9Volume = 0.05f;
    public AudioClip actionMusic10;
    [Range(0, 1)] public float actionMusic10Volume = 0.05f;
    public AudioClip actionMusic11;
    [Range(0, 1)] public float actionMusic11Volume = 0.05f;
    public AudioClip actionMusic12;
    [Range(0, 1)] public float actionMusic12Volume = 0.05f;
    public AudioClip actionMusic13;
    [Range(0, 1)] public float actionMusic13Volume = 0.05f;
    public AudioClip actionMusic14;
    [Range(0, 1)] public float actionMusic14Volume = 0.05f;
    public AudioClip actionMusic15;
    [Range(0, 1)] public float actionMusic15Volume = 0.05f;
    public AudioClip actionMusic16;
    [Range(0, 1)] public float actionMusic16Volume = 0.05f;
    public AudioClip actionMusic17;
    [Range(0, 1)] public float actionMusic17Volume = 0.05f;
    public AudioClip actionMusic18;
    [Range(0, 1)] public float actionMusic18Volume = 0.05f;
    public AudioClip actionMusic19;
    [Range(0, 1)] public float actionMusic19Volume = 0.05f;
    public AudioClip actionMusic20;
    [Range(0, 1)] public float actionMusic20Volume = 0.05f;
    public AudioClip actionMusic21;
    [Range(0, 1)] public float actionMusic21Volume = 0.05f;
    public AudioClip actionMusic22;
    [Range(0, 1)] public float actionMusic22Volume = 0.05f;
    public AudioClip actionMusic23;
    [Range(0, 1)] public float actionMusic23Volume = 0.05f;
    public AudioClip actionMusic24;
    [Range(0, 1)] public float actionMusic24Volume = 0.05f;
    public AudioClip actionMusic25;
    [Range(0, 1)] public float actionMusic25Volume = 0.05f;
    public AudioClip actionMusic26;
    [Range(0, 1)] public float actionMusic26Volume = 0.05f;
    public AudioClip actionMusic27;
    [Range(0, 1)] public float actionMusic27Volume = 0.05f;
    public AudioClip actionMusic28;
    [Range(0, 1)] public float actionMusic28Volume = 0.05f;
    public AudioClip actionMusic29;
    [Range(0, 1)] public float actionMusic29Volume = 0.05f;
    public AudioClip actionMusic30;
    [Range(0, 1)] public float actionMusic30Volume = 0.05f;
    public AudioClip actionMusic31;
    [Range(0, 1)] public float actionMusic31Volume = 0.05f;
    public AudioClip actionMusic32;
    [Range(0, 1)] public float actionMusic32Volume = 0.05f;
    public AudioClip actionMusic33;
    [Range(0, 1)] public float actionMusic33Volume = 0.05f;
    public AudioClip actionMusic34;
    [Range(0, 1)] public float actionMusic34Volume = 0.05f;
    public AudioClip actionMusic35;
    [Range(0, 1)] public float actionMusic35Volume = 0.05f;
    public AudioClip actionMusic36;
    [Range(0, 1)] public float actionMusic36Volume = 0.05f;
    public AudioClip actionMusic37;
    [Range(0, 1)] public float actionMusic37Volume = 0.05f;
    public AudioClip actionMusic38;
    [Range(0, 1)] public float actionMusic38Volume = 0.05f;
    public AudioClip actionMusic39;
    [Range(0, 1)] public float actionMusic39Volume = 0.05f;
    public AudioClip actionMusic40;
    [Range(0, 1)] public float actionMusic40Volume = 0.05f;
    public AudioClip actionMusic41;
    [Range(0, 1)] public float actionMusic41Volume = 0.05f;
    public AudioClip actionMusic42;
    [Range(0, 1)] public float actionMusic42Volume = 0.05f;
    public AudioClip actionMusic43;
    [Range(0, 1)] public float actionMusic43Volume = 0.05f;
    public AudioClip actionMusic44;
    [Range(0, 1)] public float actionMusic44Volume = 0.05f;
    public AudioClip actionMusic45;
    [Range(0, 1)] public float actionMusic45Volume = 0.05f;
    public AudioClip actionMusic46;
    [Range(0, 1)] public float actionMusic46Volume = 0.05f;
    public AudioClip actionMusic47;
    [Range(0, 1)] public float actionMusic47Volume = 0.05f;
}
